name: Build Maritime Tiles and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      osm_region:
        description: 'OSM region (e.g., portugal, spain)'
        required: false
        default: 'portugal'
        type: string
      bbox:
        description: 'Bounding box (minLon,minLat,maxLon,maxLat)'
        required: false
        default: '-9.831,37.692,-8.433,38.982'
        type: string
      tile_url:
        description: 'Tile server URL for tilepack'
        required: false
        default: 'https://t1.openseamap.org/seamark/{z}/{x}/{y}.png'
        type: string
      min_zoom:
        description: 'Minimum zoom level'
        required: false
        default: '0'
        type: string
      max_zoom:
        description: 'Maximum zoom level'
        required: false
        default: '14'
        type: string
      build_vector:
        description: 'Build vector tiles with tilemaker'
        required: false
        default: true
        type: boolean
      build_raster:
        description: 'Build raster tiles with tilepack'
        required: false
        default: true
        type: boolean

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-vector-tiles:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_vector != 'false' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup environment
      run: |
        echo "OSM_REGION=${{ github.event.inputs.osm_region || 'portugal' }}" >> $GITHUB_ENV

    - name: Cache data directory
      uses: actions/cache@v4
      with:
        path: |
          data/cache
          data/osm
          data/coastline
        key: ${{ runner.os }}-data-${{ hashFiles('scripts/download_data.sh') }}
        restore-keys: |
          ${{ runner.os }}-data-

    - name: Download tilemaker
      run: |
        wget -O tilemaker.zip https://github.com/systemed/tilemaker/releases/download/v3.0.0/tilemaker-ubuntu-22.04.zip
        unzip tilemaker.zip
        sudo mv build/tilemaker /usr/local/bin/
        rm -rf build tilemaker.zip

    - name: Download OSM data
      run: |
        mkdir -p data/osm data/coastline data/cache
        chmod +x scripts/download_data.sh
        ./scripts/download_data.sh ${{ env.OSM_REGION }}

    - name: Build vector tiles
      run: |
        chmod +x scripts/build_tiles.sh
        ./scripts/build_tiles.sh

    - name: Validate vector tiles
      run: |
        chmod +x scripts/validate_tiles.sh
        ./scripts/validate_tiles.sh

    - name: Upload vector tiles artifact
      uses: actions/upload-artifact@v4
      with:
        name: vector-tiles
        path: output/tiles/portugal_maritime.pmtiles
        retention-days: 1

  build-raster-tiles:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_raster != 'false' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup environment
      run: |
        echo "BBOX=${{ github.event.inputs.bbox || '-9.5,36.9,-6.2,42.2' }}" >> $GITHUB_ENV
        echo "TILE_URL=${{ github.event.inputs.tile_url || 'https://t1.openseamap.org/seamark/{z}/{x}/{y}.png' }}" >> $GITHUB_ENV
        echo "MIN_ZOOM=${{ github.event.inputs.min_zoom || '0' }}" >> $GITHUB_ENV
        echo "MAX_ZOOM=${{ github.event.inputs.max_zoom || '14' }}" >> $GITHUB_ENV

    - name: Download tilepack
      run: |
        # Install Homebrew
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "$HOME/.linuxbrew/bin" >> $GITHUB_PATH
        
        # Install tilepack via Homebrew
        brew tap eknowles/tools
        brew install tilepack

    - name: Download go-pmtiles
      run: |
        # Install pmtiles via Homebrew
        brew install pmtiles

    - name: Build raster tiles
      run: |
        mkdir -p output/tiles
        chmod +x scripts/build_tilepack.sh
        
        # Build raster tiles from OpenSeaMap
        ./scripts/build_tilepack.sh \
          "${{ env.TILE_URL }}" \
          "output/tiles/openseamap_raster.pmtiles" \
          "${{ env.MIN_ZOOM }}" \
          "${{ env.MAX_ZOOM }}" \
          "${{ env.BBOX }}" \
          "20"

    - name: Upload raster tiles artifact
      uses: actions/upload-artifact@v4
      with:
        name: raster-tiles
        path: output/tiles/openseamap_raster.pmtiles
        retention-days: 1

  deploy:
    needs: [build-vector-tiles, build-raster-tiles]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create deployment directory
      run: |
        mkdir -p dist

    - name: Download vector tiles
      uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: vector-tiles
        path: dist/

    - name: Download raster tiles
      uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: raster-tiles
        path: dist/

    - name: Copy configuration files
      run: |
        cp config/maplibre-style.js dist/ || true
        cp config/maplibre-style.json dist/ || true

    - name: Copy index.html
      run: cp index.html dist/

    - name: Ensure dist directory has content
      run: |
        echo "Dist directory contents:"
        ls -la dist/ || echo "Dist directory is empty"
        
        # Create a placeholder if no tiles were downloaded
        if [ ! -f "dist/portugal_maritime.pmtiles" ] && [ ! -f "dist/openseamap_raster.pmtiles" ]; then
          echo "No tile files found, creating placeholder"
          echo "No tiles available" > dist/placeholder.txt
        fi

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
